name: Build LaTeX Documents

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache TeX Live packages
      uses: actions/cache@v3
      with:
        path: /usr/local/texlive
        key: texlive-${{ runner.os }}-${{ hashFiles('**/*.tex') }}
        restore-keys: |
          texlive-${{ runner.os }}-

    - name: Set up LaTeX environment
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full

    - name: Create output directory
      run: mkdir -p output

    - name: Ensure write permissions
      run: chmod -R 777 output

    - name: Build Worksheet PDF (First Pass)
      run: pdflatex -interaction=nonstopmode -output-directory=output worksheet.tex

    - name: Build Worksheet PDF (Second Pass)
      run: pdflatex -interaction=nonstopmode -output-directory=output worksheet.tex

    - name: Build Exam PDF (First Pass)
      run: pdflatex -interaction=nonstopmode -output-directory=output exam.tex

    - name: Build Exam PDF (Second Pass)
      run: pdflatex -interaction=nonstopmode -output-directory=output exam.tex

    - name: Upload PDF Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: built-pdfs
        path: |
          output/worksheet.pdf
          output/exam.pdf
